import numberInputSettings from './numberInputSettings.js'

export default {
  detLabel: true,
  detLabelOnly: false,
  borderForTypes: false,
  includeBarcode: true,
  includeQRCode: false,
  barcodeOnMain: false,
  qrCodeErrorLevel: 'Q',
  qrCodeOnDetLabels: false,
  includeTaxonAuthorities: false,
  excludeNoCatnums: false,
  includeFieldNumber: false,
  includeCollectorInSort: false,
  underline: false,
  italics: false,
  includeStageSexOnMainLabel: false,
  font: 'Roboto Condensed',
  fontSize: 4,
  fontWeight: 400,
  lineHeight: numberInputSettings.lineHeight.default,
  labelSize: '15x7',
  labelWidth: 1.5,
  labelHeight: 0.7,
  qrCodeDims: numberInputSettings.qrCodeDims.default,
  zoom: 1,
  labelPerSpecimen: true,
  useRomanNumeralMonths: true
}
