import numberInputSettings from './numberInputSettings.js'

export default {
  showCollectionName: false,
  collectionName: null,
  labelPerSpecimen: false,
  useRomanNumeralMonths: false,
  detLabel: true,
  detLabelOnly: false,
  italicizeNames: false,
  showStorage: false,
  includePunch: false,
  includeQRCode: false,
  qrCodeErrorLevel: 'Q',
  qrCodeOnDetLabels: false,
  includeTaxonAuthorities: false,
  excludeNoCatnums: false,
  includeFieldNumber: false,
  includeCollectorInSort: false,
  underline: false,
  italics: false,
  addPrintedDate: false,
  includeProject: false,
  includeStageSexOnMainLabel: false,
  font: 'Roboto Condensed',
  fontSize: numberInputSettings.fontSize.default,
  fontWeight: 400,
  lineHeight: numberInputSettings.lineHeight.default,
  labelWidth: numberInputSettings.labelWidth.default,
  qrCodeDims: numberInputSettings.qrCodeDims.default,
  zoom: 1
}