const exampleData = [
  {
    catalogNumber: 'J234234',
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2548",
    "COLLDD": 12,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia",
    "SPECIES": "Cyphia sylvatica Eckl. var. sylvatica",
    "MAJORAREA": "Northern Cape",
    "LOCNOTES": "Namaqualand District; Steinkopf tower, N of Steinkopf.",
    "QDS": "2917BA",
    "ALT": 903,
    "LLRES": "50m",
    "LAT": 29.14359,
    "LONG": 17.44420,
    "LLUNIT": "DMS",
    "VEGCD": "succulent karroo",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "",
    "LITHCD": "quartzite",
    "EXPOSCD": "full sun",
    "ASP": "E",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb/Twiner.",
    "HABITATTXT": "Mountain slope. Vegetation type: Namaqualand Shale Shrubland. Slope: gentle.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2551",
    "COLLDD": 13,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia",
    "SPECIES": "Cyphia sylvatica Eckl. var. sylvatica",
    "MAJORAREA": "Northern Cape",
    "LOCNOTES": "Namaqualand District; Nigramoep-Bulletrap road.",
    "QDS": "2917BC",
    "ALT": 785,
    "LLRES": "50m",
    "LAT": 29.27329,
    "LONG": 17.43008,
    "LLUNIT": "DMS",
    "VEGCD": "succulent karroo",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "sand",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "NW",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb/Twiner.",
    "HABITATTXT": "Hill slope. Vegetation type: Namaqualand Klipkoppe Shrubland. Slope: gentle.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2553",
    "COLLDD": 14,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia",
    "SPECIES": "Cyphia sylvatica Eckl. var. sylvatica",
    "MAJORAREA": "Northern Cape",
    "LOCNOTES": "Namaqualand District; Nigramoep.",
    "QDS": "2917DA",
    "ALT": 830,
    "LLRES": "50m",
    "LAT": 29.3228,
    "LONG": 17.35361,
    "LLUNIT": "DMS",
    "VEGCD": "succulent karroo",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "sand",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "W",
    "BIOEFFCD": "",
    "PLANTDESC": "Herb/Climber.",
    "HABITATTXT": "Mountain slope. Vegetation type: Namaqualand Shale Shrubland. Slope: gentle.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2556",
    "COLLDD": 16,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia (cyphia)",
    "SPECIES": "Cyphia sylvatica Eckl. var. sylvatica",
    "MAJORAREA": "Northern Cape",
    "LOCNOTES": "Namaqualand District; S of Garies on road to Kotzesrus (Farm Dikdoorn).",
    "QDS": "3017DB",
    "ALT": 155,
    "LLRES": "50m",
    "LAT": 30.44489,
    "LONG": 17.58557,
    "LLUNIT": "DMS",
    "VEGCD": "succulent karroo",
    "SUBSTRCD": "soil",
    "MSTCD": "well-drained",
    "SOILCD": "sand",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb/Climber.",
    "HABITATTXT": "Plain. Vegetation type: Namaqualand Heuweltjieveld. Slope: none.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2558",
    "COLLDD": 16,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia x 2 ",
    "SPECIES": "Cyphia sylvatica Eckl. var. sylvatica",
    "MAJORAREA": "Northern Cape",
    "LOCNOTES": "Namaqualand District; NE of Kotzesrus.",
    "QDS": "3017DD",
    "ALT": 158,
    "LLRES": "50m",
    "LAT": 30.54536,
    "LONG": 17.52451,
    "LLUNIT": "DMS",
    "VEGCD": "succulent karroo",
    "SUBSTRCD": "soil",
    "MSTCD": "well-drained",
    "SOILCD": "sand",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb/Climber.",
    "HABITATTXT": "Plain. Vegetation type: Namaqualand Strandveld.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2558B",
    "COLLDD": 16,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia klein bekkie",
    "SPECIES": "Cyphia sylvatica Eckl. var. sylvatica",
    "MAJORAREA": "Northern Cape",
    "LOCNOTES": "Namaqualand District; NE of Kotzesrus.",
    "QDS": "3017DD",
    "ALT": 158,
    "LLRES": "50m",
    "LAT": 30.54536,
    "LONG": 17.52451,
    "LLUNIT": "DMS",
    "VEGCD": "succulent karroo",
    "SUBSTRCD": "soil",
    "MSTCD": "well-drained",
    "SOILCD": "sand",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "",
    "HABITATTXT": "",
    "FLRCD": "",
    "FRTCD": "",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2561",
    "COLLDD": 17,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia (cyphia)",
    "SPECIES": "Cyphia longifolia N.E.Br. var. longifolia",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Vanrhynsdorp District; Kobee road, E side of Kobee Pass.",
    "QDS": "3119CA",
    "ALT": 349,
    "LLRES": "50m",
    "LAT": 31.38195,
    "LONG": 19.01291,
    "LLUNIT": "DMS",
    "VEGCD": "fynbos",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "clay",
    "LITHCD": "shale",
    "EXPOSCD": "full sun",
    "ASP": "W",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Climber. Twiner in Eriocephalus/Pteronia.",
    "HABITATTXT": "Mountain slope. Vegetation type: Vanrhynsdorp Shale Renosterveld.  Moisture regime: Well-drained to moist/damp. Slope: moderate.",
    "FLRCD": "present",
    "FRTCD": "present",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2562",
    "COLLDD": 17,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphiaz (cyphia)",
    "SPECIES": "Cyphia zeyheriana C.Presl ex Eckl. & Zeyh.",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Vanrhynsdorp District; Kobee road, E side of Kobee Pass.",
    "QDS": "3119CA",
    "ALT": 362,
    "LLRES": "50m",
    "LAT": 31.38166,
    "LONG": 19.01242,
    "LLUNIT": "DMS",
    "VEGCD": "fynbos",
    "SUBSTRCD": "soil",
    "MSTCD": "well-drained",
    "SOILCD": "sandy loam",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb.",
    "HABITATTXT": "Plain. Vegetation type: Vanrhynsdorp Shale Renosterveld. Slope: none.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2563",
    "COLLDD": 17,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia vlakte (cyphia)",
    "SPECIES": "Cyphia zeyheriana C.Presl ex Eckl. & Zeyh.",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Vanrhynsdorp District; on plains - Kobee road back to Vanrhynsdorp (N7).",
    "QDS": "3118DB",
    "ALT": 203,
    "LLRES": "50m",
    "LAT": 31.3426,
    "LONG": 18.54211,
    "LLUNIT": "DMS",
    "VEGCD": "succulent karroo",
    "SUBSTRCD": "soil",
    "MSTCD": "well-drained",
    "SOILCD": "sand",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb. Pale lilac flowers. Ciliate flowers (petals) almost no calyx tube.",
    "HABITATTXT": "Plain. Vegetation type: Vanrhynsdorp Gannabosveld. Slope: none.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": "lilac"
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2565",
    "COLLDD": 17,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia grootblaar",
    "SPECIES": "Cyphia zeyheriana C.Presl ex Eckl. & Zeyh.",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Vanrhynsdorp District; Gifberg; Vaalsyfer.",
    "QDS": "3118DD",
    "ALT": 449,
    "LLRES": "50m",
    "LAT": 31.48144,
    "LONG": 18.54381,
    "LLUNIT": "DMS",
    "VEGCD": "fynbos",
    "SUBSTRCD": "soil",
    "MSTCD": "well-drained",
    "SOILCD": "sand",
    "LITHCD": "sandstone",
    "EXPOSCD": "full sun",
    "ASP": "",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb.",
    "HABITATTXT": "Plateau. Vegetation type: Bokkeveld Sandstone Fynbos. Slope: none.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2566",
    "COLLDD": 17,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia klein gif",
    "SPECIES": "Cyphia zeyheriana C.Presl ex Eckl. & Zeyh.",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Vanrhynsdorp District; Gifberg; Vaalsyfer.",
    "QDS": "3118DD",
    "ALT": 435,
    "LLRES": "50m",
    "LAT": 31.48158,
    "LONG": 18.54279,
    "LLUNIT": "DMS",
    "VEGCD": "fynbos",
    "SUBSTRCD": "soil",
    "MSTCD": "well-drained",
    "SOILCD": "sand",
    "LITHCD": "sandstone",
    "EXPOSCD": "full sun",
    "ASP": "",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb.",
    "HABITATTXT": "Plateau. Vegetation type: Bokkeveld Sandstone Fynbos. Slope: none.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2568",
    "COLLDD": 18,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia",
    "SPECIES": "Cyphia zeyheriana C.Presl ex Eckl. & Zeyh.",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Clanwilliam District; on road to Rietrylaagte Farm from N7.",
    "QDS": "3118DC",
    "ALT": 327,
    "LLRES": "50m",
    "LAT": 31.51505,
    "LONG": 18.35326,
    "LLUNIT": "DMS",
    "VEGCD": "succulent karroo",
    "SUBSTRCD": "soil",
    "MSTCD": "well-drained",
    "SOILCD": "sand",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "",
    "BIOEFFCD": "",
    "PLANTDESC": "Herb. Calyx tube very short, dark anthers.",
    "HABITATTXT": "Plain. Vegetation type: Doringrivier Quartzite Karoo. Slope: none.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2572",
    "COLLDD": 19,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia (knersvlakte)",
    "SPECIES": "Cyphia zeyheriana C.Presl ex Eckl. & Zeyh.",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Vanrhynsdorp District; Rooiberg, on  Beeswater gravel road W of N7.",
    "QDS": "3118BC",
    "ALT": 102,
    "LLRES": "50m",
    "LAT": 31.25131,
    "LONG": 18.35299,
    "LLUNIT": "DMS",
    "VEGCD": "succulent karroo",
    "SUBSTRCD": "soil",
    "MSTCD": "well-drained",
    "SOILCD": "",
    "LITHCD": "quartzite",
    "EXPOSCD": "full sun",
    "ASP": "NW",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb/Geophyte. Plant height: 15 cm. 3 Upper petals with dark purple dots.",
    "HABITATTXT": "Plain. Vegetation type: Central Knersvlakte Vygieveld. Soil: Silt. Slope: gentle.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2573",
    "COLLDD": 19,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia 2",
    "SPECIES": "Cyphia zeyheriana C.Presl ex Eckl. & Zeyh.",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Vanrhynsdorp District; Rooiberg, on  Beeswater gravel road W of N7.",
    "QDS": "3118BC",
    "ALT": 101,
    "LLRES": "50m",
    "LAT": 31.25191,
    "LONG": 18.35313,
    "LLUNIT": "DMS",
    "VEGCD": "succulent karroo",
    "SUBSTRCD": "soil",
    "MSTCD": "well-drained",
    "SOILCD": "sand",
    "LITHCD": "quartzite",
    "EXPOSCD": "full sun",
    "ASP": "NW",
    "BIOEFFCD": "disturbed-other",
    "PLANTDESC": "Herb/Geophyte. Plant height: 15 cm. Erect herb with soft elongated bulb; 3 upper petals with dark purple markings.",
    "HABITATTXT": "Plain. Vegetation type: Central Knersvlakte Vygieveld.  Slope: gentle.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2575",
    "COLLDD": 19,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia grootblaar (cyphia)",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Clanwilliam District; Rietrylaagte; at back of Patrys Cottage.",
    "QDS": "3118DC",
    "ALT": 220,
    "LLRES": "50m",
    "LAT": 31.76706,
    "LONG": 18.55978,
    "LLUNIT": "DD",
    "VEGCD": "succulent karroo",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "sand",
    "LITHCD": "sandstone",
    "EXPOSCD": "full sun",
    "ASP": "",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb/Twiner; lanceolate (3-lobed) leaves. Solitary flower; 3 upper petals with one dot each.",
    "HABITATTXT": "Hill slope. Vegetation type: Leipoldtville Sand Fynbos.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2576",
    "COLLDD": 19,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia 5-kol",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Clanwilliam District; Rietrylaagte, at back of Patrys Cottage.",
    "QDS": "3118DC",
    "ALT": 220,
    "LLRES": "50m",
    "LAT": 31.86706,
    "LONG": 18.55978,
    "LLUNIT": "DD",
    "VEGCD": "succulent karroo",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "sandy loam",
    "LITHCD": "sandstone",
    "EXPOSCD": "full sun",
    "ASP": "NW",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb/Geophyte. All 5 petals with purple marking.",
    "HABITATTXT": "Hill slope. Vegetation type: Leipoldtville Sand Fynbos. Soil/stony soil. Slope: gentle.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2579",
    "COLLDD": 20,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia valubilis",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Northern Cape",
    "LOCNOTES": "Calvinia District; on Moedverloor road between Nieuwoudtville and Clanwilliam.",
    "QDS": "3119CA",
    "ALT": 805,
    "LLRES": "50m",
    "LAT": 31.39143,
    "LONG": 19.08125,
    "LLUNIT": "DMS",
    "VEGCD": "fynbos",
    "SUBSTRCD": "soil",
    "MSTCD": "well-drained",
    "SOILCD": "sand",
    "LITHCD": "sandstone",
    "EXPOSCD": "full sun",
    "ASP": "",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb/Climber.",
    "HABITATTXT": "Plain. Vegetation type: Bokkeveld Sandstone Fynbos. Slope: none.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2581",
    "COLLDD": 21,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Clanwilliam District; parking at top of Pakhuis Pass.",
    "QDS": "3219AA",
    "ALT": 900,
    "LLRES": "50m",
    "LAT": 32.15,
    "LONG": 19.03027778,
    "LLUNIT": "DD",
    "VEGCD": "fynbos",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "sandy loam",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "S",
    "BIOEFFCD": "disturbed-other",
    "PLANTDESC": "Herb/Climber. Lower petals 'turned' out; 3 purple dots.",
    "HABITATTXT": "Mountain slope. Vegetation type: Cederberg Sandstone Fynbos. Slope: gentle.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2582",
    "COLLDD": 21,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia (cyphiella)",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Clanwilliam District. Pakhuis Pass; on track to Heuningvlei.",
    "QDS": "3219AA",
    "ALT": null,
    "LLRES": "1/4dg",
    "LAT": 32.073,
    "LONG": 19.073,
    "LLUNIT": "DMS",
    "VEGCD": "fynbos",
    "SUBSTRCD": "soil",
    "MSTCD": "well-drained",
    "SOILCD": "sand",
    "LITHCD": "sandstone",
    "EXPOSCD": "full sun",
    "ASP": "NE",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb/Climber. Pale magenta flowers. Robust, climber with brittle stem. Leaves deeply lobed/ incised; rosette of leaves at ground level.",
    "HABITATTXT": "Mountain slope. Vegetation type: Cederberg Sandstone Fynbos. Slope: gentle.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2583",
    "COLLDD": 21,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia LY",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Clanwilliam District. At turn-off to Wupperthal/Biedouw Valley.",
    "QDS": "3219AA",
    "ALT": 560,
    "LLRES": "50m",
    "LAT": 32.0664,
    "LONG": 19.12889,
    "LLUNIT": "DD",
    "VEGCD": "nama karoo",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "sand",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "W",
    "BIOEFFCD": "disturbed-other",
    "PLANTDESC": "Herb/Climber. Pure white flowers, solitary.",
    "HABITATTXT": "Hill slope. Vegetation type: Cederberg Sandstone Fynbos. Slope: gentle.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": "white"
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2584",
    "COLLDD": 21,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia (cyphia)",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Clanwilliam District; at parking at top of Pakhuis Pass.",
    "QDS": "3219AA",
    "ALT": 900,
    "LLRES": "50m",
    "LAT": 32.1501,
    "LONG": 19.0304,
    "LLUNIT": "DD",
    "VEGCD": "fynbos",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "sand",
    "LITHCD": "sandstone",
    "EXPOSCD": "full sun",
    "ASP": "",
    "BIOEFFCD": "disturbed-other",
    "PLANTDESC": "Herb/Climber. White flowers with 3 maroon dots on upper petals.",
    "HABITATTXT": "Mountain peak. Vegetation type: Cederberg Sandstone Fynbos. Slope: none.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": "white"
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2585",
    "COLLDD": 21,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia (cyphia)",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Clanwilliam District. On Boskloof road E of Clanwilliam.",
    "QDS": "3218BB",
    "ALT": 180,
    "LLRES": "",
    "LAT": 32.17755,
    "LONG": 18.91223,
    "LLUNIT": "DD",
    "VEGCD": "fynbos",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "sandy loam",
    "LITHCD": "shale",
    "EXPOSCD": "full sun",
    "ASP": "W",
    "BIOEFFCD": "roadside/railwayside",
    "PLANTDESC": "Herb/Climber. Whitish flowers with 3 magenta dots.",
    "HABITATTXT": "Hill slope. Vegetation type: Citrusdal Vygieveld. Biome: Fynbos/Nama Karoo.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": "white"
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2588",
    "COLLDD": 23,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Wit Cyphia",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Clanwilliam District. On Boskloof road E of Clanwilliam.",
    "QDS": "3218BB",
    "ALT": 180,
    "LLRES": "50m",
    "LAT": 32.17755,
    "LONG": 18.91223,
    "LLUNIT": "DD",
    "VEGCD": "nama karoo",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "sandy loam",
    "LITHCD": "shale",
    "EXPOSCD": "full sun",
    "ASP": "W",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb/Climber.",
    "HABITATTXT": "Hill slope. Vegetation type: Citrusdal Vygieveld. Slope: gentle.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": "white"
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2589",
    "COLLDD": 23,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia Worcester",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Worcester District; Worcester, Karoo Botanical Garden.",
    "QDS": "3319CB",
    "ALT": 400,
    "LLRES": "50m",
    "LAT": 33.61457,
    "LONG": 19.45152,
    "LLUNIT": "DD",
    "VEGCD": "succulent karroo",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "sandy loam",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "W",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb/Climber. White flowers with magenta markings on upper 3 petals.",
    "HABITATTXT": "Hill slope. Vegetation type: Robertston Karoo. Slope: gentle.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": "white"
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2590",
    "COLLDD": 25,
    "COLLMM": 8,
    "COLLYY": 2020,
    "TMPNAME": "Cyphia groot wit",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Strand District; Harold Porter National Botanical Garden.",
    "QDS": "3418BD",
    "ALT": null,
    "LLRES": "50m",
    "LAT": 34.34591,
    "LONG": 18.92668,
    "LLUNIT": "DD",
    "VEGCD": "fynbos",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "sand",
    "LITHCD": "sandstone",
    "EXPOSCD": "full sun",
    "ASP": "S",
    "BIOEFFCD": "recently burned",
    "PLANTDESC": "Herb/Climber.",
    "HABITATTXT": "Mountain slope. Vegetation type: Kogelberg Sandstone Fynbos. Slope: moderate.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2666",
    "COLLDD": 29,
    "COLLMM": 8,
    "COLLYY": 2021,
    "TMPNAME": "Cyphia cf. longiflora",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Northen Cape",
    "LOCNOTES": "Namaqualand District. Road between Bulletrap and Niagramoep.",
    "QDS": "2917BC",
    "ALT": 830,
    "LLRES": "50m",
    "LAT": 29.458939,
    "LONG": 17.716474,
    "LLUNIT": "DD",
    "VEGCD": "succulent karroo",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb.",
    "HABITATTXT": "Mountain slope. Namaqualand Shale Shrubland. Slope: gentle.",
    "FLRCD": "",
    "FRTCD": "present",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2667",
    "COLLDD": 29,
    "COLLMM": 8,
    "COLLYY": 2021,
    "TMPNAME": "Cyphia longiflora",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Northen Cape",
    "LOCNOTES": "Namaqualand District. Road between Bulletrap and Niagramoep.",
    "QDS": "2917BC",
    "ALT": 880,
    "LLRES": "250m",
    "LAT": 29.2734,
    "LONG": 17.42449,
    "LLUNIT": "DMS",
    "VEGCD": "succulent karroo",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb. Linear leaves not crispate.",
    "HABITATTXT": "Mountain slope. Namaqualand Shale Shrubland. Slope: gentle.",
    "FLRCD": "",
    "FRTCD": "present",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2679",
    "COLLDD": 31,
    "COLLMM": 8,
    "COLLYY": 2021,
    "TMPNAME": "Cyphia 3-lobed",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Northen Cape",
    "LOCNOTES": "Namaqualand District, on road between Bulletrap and Nigramoep.",
    "QDS": "2917BC",
    "ALT": 883,
    "LLRES": "50m",
    "LAT": 29.462752,
    "LONG": 17.630027,
    "LLUNIT": "DD",
    "VEGCD": "succulent karroo",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "",
    "BIOEFFCD": "road/rail cutting",
    "PLANTDESC": "Herb/Climber. Leaves 3-lobed (incised lobes).",
    "HABITATTXT": "Plain. Namaqualand Shale Shrubland. Slope: none. Plain covered with stones.",
    "FLRCD": "",
    "FRTCD": "present",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2680",
    "COLLDD": 1,
    "COLLMM": 9,
    "COLLYY": 2021,
    "TMPNAME": "Cyphia cff. longiflora",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Northen Cape",
    "LOCNOTES": "Namaqualand District, on road between Bulletrap and Nigramoep, between Graskloof and Vaalwater.",
    "QDS": "2901DA",
    "ALT": 889,
    "LLRES": "50m",
    "LAT": 29.511504,
    "LONG": 1.596816,
    "LLUNIT": "DD",
    "VEGCD": "succulent karroo",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "E",
    "BIOEFFCD": "road/rail cutting",
    "PLANTDESC": "Herb/geophyte. Flowers lilac wit darker markings on all 5 petals. Leaves crenate, not lobed.",
    "HABITATTXT": "Mountain slope. Namaqualand Granite Renosterveld. Fynbos. Slope: gentle.",
    "FLRCD": "present",
    "FRTCD": "present",
    "FLCLRS": "lilac"
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2681",
    "COLLDD": 1,
    "COLLMM": 9,
    "COLLYY": 2021,
    "TMPNAME": "Cyphia digitata",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Northen Cape",
    "LOCNOTES": "Namaqualand District, on road between Bulletrap and Nigramoep.",
    "QDS": "2917DA",
    "ALT": 889,
    "LLRES": "50m",
    "LAT": 29.511504,
    "LONG": 17.596816,
    "LLUNIT": "DD",
    "VEGCD": "fynbos",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "S",
    "BIOEFFCD": "road/rail cutting",
    "PLANTDESC": "Herb/geophyte. White flowers, short-tubed with elongated purple markings on top of 3 petals. Corolla swollen at base.",
    "HABITATTXT": "Mountain slope. Namaqualand Granite Renosterveld. Slope: gentle.",
    "FLRCD": "present",
    "FRTCD": "present",
    "FLCLRS": "white"
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2683",
    "COLLDD": 1,
    "COLLMM": 9,
    "COLLYY": 2021,
    "TMPNAME": "Cyphia cf. longiflora",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Northen Cape",
    "LOCNOTES": "Namaqualand District, Nigramoep road cutting.",
    "QDS": "2917DA",
    "ALT": 774,
    "LLRES": "50m",
    "LAT": 29.575723,
    "LONG": 17.594594,
    "LLUNIT": "DD",
    "VEGCD": "succulent karroo",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "NW",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb/geophyte.",
    "HABITATTXT": "Plateau. Namaqualand Shale Shrubland. Slope: gentle. Aspectd: W-NW.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2682",
    "COLLDD": 1,
    "COLLMM": 9,
    "COLLYY": 2021,
    "TMPNAME": "Cyphia cf.longiflora",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Northen Cape",
    "LOCNOTES": "Namaqualand District. Nigramoep on road wouth of  houses, between Nigramoep and Kasteelberg turn-off.",
    "QDS": "2917DA",
    "ALT": 727,
    "LLRES": "50m",
    "LAT": 29.543798,
    "LONG": 17.581438,
    "LLUNIT": "DD",
    "VEGCD": "",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "NW",
    "BIOEFFCD": "",
    "PLANTDESC": "Herb/geophyte.",
    "HABITATTXT": "Plain. Namaqualand Kipkoppe Shrubland. Slope: gentle.",
    "FLRCD": "present",
    "FRTCD": "present",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2686",
    "COLLDD": 1,
    "COLLMM": 9,
    "COLLYY": 2021,
    "TMPNAME": "Cyphia cf. longiflora",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Northen Cape",
    "LOCNOTES": "Namaqualand District. Ridge to SW of Nigramoep's houses.",
    "QDS": "2917BC",
    "ALT": 729,
    "LLRES": "50m",
    "LAT": 29.32252,
    "LONG": 17.54529,
    "LLUNIT": "DD",
    "VEGCD": "succulent karroo",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "E",
    "BIOEFFCD": "grazed",
    "PLANTDESC": "Herb.",
    "HABITATTXT": "Mountain slope. Namaqualand Kipkoppe Shrubland. Slope: gentle.",
    "FLRCD": "present",
    "FRTCD": "present",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2699",
    "COLLDD": 3,
    "COLLMM": 10,
    "COLLYY": 2021,
    "TMPNAME": "Cyphia regop",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Clanwilliam District. Grey's Pass (northern part); just below Piekenierskloof Pass.",
    "QDS": "3218DB",
    "ALT": 380,
    "LLRES": "50m",
    "LAT": 32.61527,
    "LONG": 18.98595,
    "LLUNIT": "DD",
    "VEGCD": "fynbos",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "moist/damp",
    "SOILCD": "",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "SW",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb. Plant height: 40 cm. 'Elongated' flowers, bilabiate white-light lilac. Basal rosette of leaves.",
    "HABITATTXT": "Cederberg Sandstone Fynbos. Slope: steep.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2702",
    "COLLDD": 4,
    "COLLMM": 10,
    "COLLYY": 2021,
    "TMPNAME": "Cyphia paleisheuwel",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Clanwilliam District, Paleisheuwel road from turn-off on N7; just S of Mieliedraai.",
    "QDS": "3218BD",
    "ALT": 317,
    "LLRES": "50m",
    "LAT": 32.29482,
    "LONG": 18.50248,
    "LLUNIT": "DMS",
    "VEGCD": "fynbos",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "E",
    "BIOEFFCD": "disturbed-other",
    "PLANTDESC": "Herb/climber.",
    "HABITATTXT": "Mountain slope. Graafwater Sandstone Fynbos. Slope: moderate.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": "magenta"
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2703",
    "COLLDD": 4,
    "COLLMM": 10,
    "COLLYY": 2021,
    "TMPNAME": "Cyphia (wit) Paarlberg",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Paarl District; Paarl Mountain Nature Reserve, on track to Bethelsdam.",
    "QDS": "3318DB",
    "ALT": 503,
    "LLRES": "50m",
    "LAT": 33.43403,
    "LONG": 18.56001,
    "LLUNIT": "DMS",
    "VEGCD": "fynbos",
    "SUBSTRCD": "soil",
    "MSTCD": "well-drained",
    "SOILCD": "",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "S",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb/climber.",
    "HABITATTXT": "Mountain slope. Boland Granite Fynbos. Slope: moderate.",
    "FLRCD": "present",
    "FRTCD": "",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2705",
    "COLLDD": 5,
    "COLLMM": 10,
    "COLLYY": 2021,
    "TMPNAME": "Cyphia ecloniana",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Caledon District, E of Caledon, Krige silo, below railway line.",
    "QDS": "3419BA",
    "ALT": 361.6,
    "LLRES": "50m",
    "LAT": 34.218918,
    "LONG": 19.594365,
    "LLUNIT": "DD",
    "VEGCD": "fynbos",
    "SUBSTRCD": "soil",
    "MSTCD": "moist/damp",
    "SOILCD": "",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "S",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb. Plant height: 25 cm. Mauve/beige flowers with maroon outside, soft, sweet scent at night.",
    "HABITATTXT": "Mountain slope/hill slope/seepage. Western Ruens Shale Renosterveld. Aspect: S-SW. Slope: moderate.",
    "FLRCD": "present",
    "FRTCD": "present",
    "FLCLRS": "mauve, beige, maroon"
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2706",
    "COLLDD": 5,
    "COLLMM": 10,
    "COLLYY": 2021,
    "TMPNAME": "Cyphia mauve/digitata",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Caledon District, E of Caledon, Krige silo, below railway line.",
    "QDS": "3419BC",
    "ALT": 363,
    "LLRES": "50m",
    "LAT": 34.28908,
    "LONG": 19.594365,
    "LLUNIT": "DD",
    "VEGCD": "fynbos",
    "SUBSTRCD": "soil",
    "MSTCD": "well-drained",
    "SOILCD": "",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "SE",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb/climber.",
    "HABITATTXT": "Mountain slope. Western Ruens Shale Renosterveld. Slope: moderate.",
    "FLRCD": "present",
    "FRTCD": "present",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2716",
    "COLLDD": 7,
    "COLLMM": 10,
    "COLLYY": 2021,
    "TMPNAME": "Cyphia digitata",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Caledon District. Along dirt road to Ou Tuin, WSW of Caledon.",
    "QDS": "3419AD",
    "ALT": 130,
    "LLRES": "50m",
    "LAT": 34.25582,
    "LONG": 19.28978,
    "LLUNIT": "DD",
    "VEGCD": "fynbos",
    "SUBSTRCD": "soil",
    "MSTCD": "well-drained",
    "SOILCD": "",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb.",
    "HABITATTXT": "Plain. Western Ruens Shale Renosterveld. Slope: none.",
    "FLRCD": "",
    "FRTCD": "present",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2722",
    "COLLDD": 9,
    "COLLMM": 10,
    "COLLYY": 2021,
    "TMPNAME": "Cyphia digitata",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Swellendam District. On R62, between Montagu and Barrydale - just E of Akkerboom.",
    "QDS": "3320DC",
    "ALT": 676,
    "LLRES": "",
    "LAT": 33.55275,
    "LONG": 20.2994,
    "LLUNIT": "DMS",
    "VEGCD": "fynbos",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "SW",
    "BIOEFFCD": "no effect seen",
    "PLANTDESC": "Herb/climber.",
    "HABITATTXT": "Hill slope. Montague Shale Fynbos. Slope: gentle.",
    "FLRCD": "",
    "FRTCD": "present",
    "FLCLRS": ""
  },
  {
    "COLLECTOR": "Steyn, H.M.",
    "NUMBER": "2723",
    "COLLDD": 9,
    "COLLMM": 10,
    "COLLYY": 2021,
    "TMPNAME": "Cyphia digitata",
    "SPECIES": "Cyphia bolusii E.Phillips",
    "MAJORAREA": "Western Cape",
    "LOCNOTES": "Swellendam District. On R62, between Montagu and Barrydale - ± 10 km W of Barrydale.",
    "QDS": "3320DC",
    "ALT": 437,
    "LLRES": "50m",
    "LAT": 33.5571,
    "LONG": 20.37156,
    "LLUNIT": "DMS",
    "VEGCD": "fynbos",
    "SUBSTRCD": "stony soil/rocky",
    "MSTCD": "well-drained",
    "SOILCD": "",
    "LITHCD": "",
    "EXPOSCD": "full sun",
    "ASP": "",
    "BIOEFFCD": "roadside/railwayside",
    "PLANTDESC": "Herb.",
    "HABITATTXT": "Hil slope. Montagu Shale Renosterveld. Slope: gentle.",
    "FLRCD": "",
    "FRTCD": "present",
    "FLCLRS": ""
  }
]
export default exampleData