const exampleData = [
  {
    "CATEGORY": "PS",
    "ACCESSION": "",
    "BARCODE": "PRE0857308-0",
    "COLLECTOR": "Burrows, J.E.",
    "PREFIX": "",
    "NUMBER": "12369",
    "SUFFIX": "",
    "ADDCOLL": "Grieve, G.R.H. & Grieve, K.W.",
    "DUPS": "PRE",
    "DAY": 2,
    "MONTH": 11,
    "YEAR": 2011,
    "COLLECTED": "02-Nov-11",
    "FAMILY": "Apocynaceae",
    "ALTFAMILY": "",
    "TAXSTAT": "acc",
    "SPECIES": "Miraglossum pulchellum (Schltr.) Kupicha",
    "FULLNAME": "Miraglossum pulchellum (Schltr.) Kupicha",
    "ACCEPTED": "",
    "CURATENAME": "",
    "DETBY": "Bester, SP",
    "DETSTATUS": "",
    "DETDAY": 0,
    "DETMONTH": 8,
    "DETYEAR": 2012,
    "DETDATE": "Aug-12",
    "PLANTDESC": "HT: 20.00, HTUNIT: cm; HT: 20.00, HTUNIT: cm; GRFRMS: Herb; GRFRMS: Geophyte",
    "COUNTRY": "South Africa",
    "MAJORAREA": "Mpumalanga",
    "LOCNOTES": "Lydenburg District. Buffelskloof Nature Reserve in front of \"Aloe Cottage\".",
    "HABITATTXT": "",
    "CULTIVATED": "No",
    "LAT": 25.172,
    "NS": "S",
    "LONG": 30.3124,
    "EW": "E",
    "LLUNIT": "DMS",
    "LLRES": "10m",
    "LLDATUM": "",
    "QDS": "2530BC",
    "LATDEC": -25.28888889,
    "LONGDEC": 30.52333333,
    "ALT": 1780,
    "ALTUNIT": "",
    "NOTES": "Perennial geophytic herb growing in recently burnt grassland among dolerite boulders. Only 4 plants seen.",
    "GENUS": "Miraglossum",
    "SP1": "pulchellum",
    "AUTHOR1": "(Schltr.) Kupicha",
    "RANK1": "",
    "SP2": "",
    "AUTHOR2": "",
    "RANK2": "",
    "SP3": "",
    "AUTHOR3": "",
    "LABELTOTAL": 0
  },
  {
    "CATEGORY": "PS",
    "ACCESSION": "",
    "BARCODE": "PRE0857424-0",
    "COLLECTOR": "Zietsman, P.C.",
    "PREFIX": "",
    "NUMBER": "5039",
    "SUFFIX": "",
    "ADDCOLL": "Zietsman, L. & Nel, E.",
    "DUPS": "PRE",
    "DAY": 7,
    "MONTH": 9,
    "YEAR": 2011,
    "COLLECTED": "07-Sep-11",
    "FAMILY": "Brassicaceae",
    "ALTFAMILY": "Cruciferae",
    "TAXSTAT": "acc",
    "SPECIES": "Heliophila remotiflora O.E.Schulz",
    "FULLNAME": "Heliophila remotiflora O.E.Schulz",
    "ACCEPTED": "",
    "CURATENAME": "",
    "DETBY": "Winter, PJD",
    "DETSTATUS": "",
    "DETDAY": 1,
    "DETMONTH": 4,
    "DETYEAR": 2015,
    "DETDATE": "01-Apr-15",
    "PLANTDESC": "HT: 25.00, HTUNIT: cm; GRFRMS: Herb",
    "COUNTRY": "South Africa",
    "MAJORAREA": "Northern Cape",
    "LOCNOTES": "Herbert. Mokala National Park. By Lilydale hek.",
    "HABITATTXT": "plain",
    "CULTIVATED": "No",
    "LAT": 29.0422,
    "NS": "S",
    "LONG": 24.2803,
    "EW": "E",
    "LLUNIT": "DMS",
    "LLRES": "100m",
    "LLDATUM": "",
    "QDS": "2924AB",
    "LATDEC": -29.07277778,
    "LONGDEC": 24.4675,
    "ALT": 1132,
    "ALTUNIT": "",
    "NOTES": "Undisturbed. No slope. Scattered.",
    "GENUS": "Heliophila",
    "SP1": "remotiflora",
    "AUTHOR1": "O.E.Schulz",
    "RANK1": "",
    "SP2": "",
    "AUTHOR2": "",
    "RANK2": "",
    "SP3": "",
    "AUTHOR3": "",
    "LABELTOTAL": 0
  },
  {
    "CATEGORY": "PS",
    "ACCESSION": "",
    "BARCODE": "PRE0857427-0",
    "COLLECTOR": "Zietsman, P.C.",
    "PREFIX": "",
    "NUMBER": "4994",
    "SUFFIX": "",
    "ADDCOLL": "Zietsman, L. & Nel, E.",
    "DUPS": "PRE",
    "DAY": 4,
    "MONTH": 9,
    "YEAR": 2011,
    "COLLECTED": "04-Sep-11",
    "FAMILY": "Scrophulariaceae",
    "ALTFAMILY": "",
    "TAXSTAT": "acc",
    "SPECIES": "Peliostomum leucorrhizum E.Mey. ex Benth.",
    "FULLNAME": "Peliostomum leucorrhizum E.Mey. ex Benth.",
    "ACCEPTED": "",
    "CURATENAME": "",
    "DETBY": "Ready, JA",
    "DETSTATUS": "",
    "DETDAY": 0,
    "DETMONTH": 2,
    "DETYEAR": 2012,
    "DETDATE": "Feb-12",
    "PLANTDESC": "HT: 10.00, HTUNIT: cm; GRFRMS: Herb",
    "COUNTRY": "South Africa",
    "MAJORAREA": "Northern Cape",
    "LOCNOTES": "Herbert. Mokala National Park. Kameeldoring loop.",
    "HABITATTXT": "plain",
    "CULTIVATED": "No",
    "LAT": 29.0539,
    "NS": "S",
    "LONG": 24.2256,
    "EW": "E",
    "LLUNIT": "DMS",
    "LLRES": "100m",
    "LLDATUM": "",
    "QDS": "2924AB",
    "LATDEC": -29.09416667,
    "LONGDEC": 24.38222222,
    "ALT": 1173,
    "ALTUNIT": "",
    "NOTES": "Undisturbed. No slope. Flowers light and dark purple. Donker pers strepe op buis van trompet. Pers kolle aan basis. Tube white in lower half, dark blue at base of lobes.",
    "GENUS": "Peliostomum",
    "SP1": "leucorrhizum",
    "AUTHOR1": "E.Mey. ex Benth.",
    "RANK1": "",
    "SP2": "",
    "AUTHOR2": "",
    "RANK2": "",
    "SP3": "",
    "AUTHOR3": "",
    "LABELTOTAL": 0
  },
  {
    "CATEGORY": "PS",
    "ACCESSION": "",
    "BARCODE": "PRE0857596-0",
    "COLLECTOR": "Zambatis, G.",
    "PREFIX": "",
    "NUMBER": "GZ 437",
    "SUFFIX": "",
    "ADDCOLL": "Zambatis, N.",
    "DUPS": "PRE",
    "DAY": 14,
    "MONTH": 11,
    "YEAR": 2010,
    "COLLECTED": "14-Nov-10",
    "FAMILY": "Agavaceae",
    "ALTFAMILY": "",
    "TAXSTAT": "syn",
    "SPECIES": "Chlorophytum angulicaule (Baker) Kativu",
    "FULLNAME": "Chlorophytum angulicaule (Baker) Kativu",
    "ACCEPTED": "Anthericum angulicaule (Baker) Kativu",
    "CURATENAME": "",
    "DETBY": "Johannesmeier, A",
    "DETSTATUS": "cf.",
    "DETDAY": 0,
    "DETMONTH": 5,
    "DETYEAR": 2011,
    "DETDATE": "May-11",
    "PLANTDESC": "HT: 60.00, HTUNIT: cm; GRFRMS: Herb",
    "COUNTRY": "South Africa",
    "MAJORAREA": "Mpumalanga",
    "LOCNOTES": "Kruger National Park. Pretoriuskop, Phabeni road.",
    "HABITATTXT": "",
    "CULTIVATED": "No",
    "LAT": 25.0038,
    "NS": "S",
    "LONG": 31.2654,
    "EW": "E",
    "LLUNIT": "DMS",
    "LLRES": "100m",
    "LLDATUM": "",
    "QDS": "2531AB",
    "LATDEC": -25.01055556,
    "LONGDEC": 31.44833333,
    "ALT": 347,
    "ALTUNIT": "",
    "NOTES": "Veld burnt last season. Slender leaves. Flowers clustered or single on slender stalk.",
    "GENUS": "Chlorophytum",
    "SP1": "angulicaule",
    "AUTHOR1": "(Baker) Kativu",
    "RANK1": "",
    "SP2": "",
    "AUTHOR2": "",
    "RANK2": "",
    "SP3": "",
    "AUTHOR3": "",
    "LABELTOTAL": 0
  },
  {
    "CATEGORY": "PS",
    "ACCESSION": "",
    "BARCODE": "PRE0857598-0",
    "COLLECTOR": "Zambatis, G.",
    "PREFIX": "",
    "NUMBER": "GZ 438",
    "SUFFIX": "",
    "ADDCOLL": "Zambatis, N.",
    "DUPS": "PRE",
    "DAY": 14,
    "MONTH": 11,
    "YEAR": 2010,
    "COLLECTED": "14-Nov-10",
    "FAMILY": "Hyacinthaceae",
    "ALTFAMILY": "",
    "TAXSTAT": "acc",
    "SPECIES": "Ledebouria luteola Jessop",
    "FULLNAME": "Ledebouria luteola Jessop",
    "ACCEPTED": "",
    "CURATENAME": "",
    "DETBY": "Johannesmeier, A",
    "DETSTATUS": "",
    "DETDAY": 0,
    "DETMONTH": 5,
    "DETYEAR": 2011,
    "DETDATE": "May-11",
    "PLANTDESC": "HT: 20.00, HTUNIT: cm; GRFRMS: Geophyte",
    "COUNTRY": "South Africa",
    "MAJORAREA": "Mpumalanga",
    "LOCNOTES": "Kruger National Park. Pretoriuskop. Dooispan road between turn-off to N'watsishika and Phabeni gate.",
    "HABITATTXT": "",
    "CULTIVATED": "No",
    "LAT": 25.0038,
    "NS": "S",
    "LONG": 31.2654,
    "EW": "E",
    "LLUNIT": "DMS",
    "LLRES": "100m",
    "LLDATUM": "",
    "QDS": "2531AB",
    "LATDEC": -25.01055556,
    "LONGDEC": 31.44833333,
    "ALT": 347,
    "ALTUNIT": "",
    "NOTES": "Veld burnt last season. Leaves not spotted. Flowers mauve and yellow-green, the petals fold back and the stamens are mauve and anthers yellow. Occasional to common where occurring.",
    "GENUS": "Ledebouria",
    "SP1": "luteola",
    "AUTHOR1": "Jessop",
    "RANK1": "",
    "SP2": "",
    "AUTHOR2": "",
    "RANK2": "",
    "SP3": "",
    "AUTHOR3": "",
    "LABELTOTAL": 3
  }
 ]
export default exampleData