const exampleData = [
  {
    "catnum": "",
    "collectorNo": "IE06-253",
    "typestatus": "",
    "country": "South Africa",
    "admin1": "Mpumalanga",
    "admin1Type": "Prov.",
    "admin2": "Carolina",
    "admin2Type": "Distr.",
    "locality": "Farm Frisgewaagd 409, Ca. 10km north of Carolina",
    "verbatimLatitude": "S25°55'09.0\"",
    "verbatimLongitude": "E30°03'44.6\"",
    "uncertainty": 200,
    "uncertaintyUnit": "m",
    "geodeticDatum": "WGS84",
    "georefSources": "GPS",
    "habitat": "Hill crest; 100% quarzite; orange, sandy soil",
    "verbatimElevation": "1725m",
    'sitecode': '',
    "permitNumber": "",
    "collectingDate": "2006/11/12 10:00–10:40",
    "startdate": "",
    "enddate": "",
    "collectors": "I. Engelbrecht (GDACE); A. Mathie; H. Claasens",
    "collectMethods": "opportunistic searching; rock turning",
    "conditions": "soil slightly damp",
    "lifeStageSexCounts": "",
    "seriesNote": "",
    "class": "Arachnida",
    "order": "Araneae",
    "family": "Theraphosidae",
    "genus": "Harpactira",
    "specificEpithet": "",
    "infraspecificEpithet": "",
    "canonicalName": "Harpactira",
    "taxonRank": "genus",
    "author": "",
    "verbatimIdentification": "",
    "dateIdentified": "2006-11-23",
    "identifiedBy": "I. Engelbrecht (GDACE)",
    "detMethod": "",
    "identificationQualifier": null,
    "identificationConfidence": '',
    "detReferences": "",
    "detNote": ""
  },
  {
    "catnum": "TM12345",
    "collectorNo": "IE11-143",
    "typestatus": "",
    "country": "South Africa",
    "admin1": "Northern Cape",
    "admin1Type": "Prov.",
    "admin2": "Noupoort",
    "admin2Type": "Distr.",
    "locality": "Caroluspoort, ca. 10km NW of Noupoort, north side of ridge alongside railwayline",
    "verbatimLatitude": "S31°07'27.5''",
    "verbatimLongitude": "E24°53'20.6''",
    "uncertainty": null,
    "uncertaintyUnit": "",
    "geodeticDatum": "WGS84",
    "georefSources": "GPS",
    "habitat": "Gentle to moderate, N facing hill base & slope; loose rocks (50 - 75% cover); 100% dolerite; open, besemkaree shrubland",
    "verbatimElevation": "",
    'sitecode': '',
    "permitNumber": "",
    "collectingDate": "2011/11/19",
    "startdate": "",
    "enddate": "",
    "collectors": "I. Engelbrecht (GDACE); K. Moir",
    "collectMethods": "UV lighting",
    "conditions": "cool, moderately windy, very dry",
    "lifeStageSexCounts": "1ad♀",
    "seriesNote": "captive reared",
    "class": "",
    "order": "",
    "family": "",
    "genus": "",
    "specificEpithet": "",
    "infraspecificEpithet": "",
    "canonicalName": "Harpactira baviana",
    "taxonRank": "species",
    "author": "Purcell, 1903",
    "verbatimIdentification": "",
    "dateIdentified": "2016-07-01",
    "identifiedBy": "I. Engelbrecht (UP)",
    "detMethod": "tacit expertise",
    "identificationQualifier": 'cf.',
    "identificationConfidence": '',
    "detReferences": "",
    "detNote": "Confirmed after topotypes collected at Hanover"
  },
  {
    "catnum": "",
    "collectorNo": "IE15-018",
    "typestatus": "paratype",
    "country": "South Africa",
    "admin1": "Eastern Cape",
    "admin1Type": "Prov.",
    "admin2": "Jansenville",
    "admin2Type": "Distr.",
    "locality": "Farm Osplaat, 18km WNW Jansenville",
    "verbatimLatitude": "S32.8772°",
    "verbatimLongitude": "E24.4952°",
    "uncertainty": 3,
    "uncertaintyUnit": "km",
    "geodeticDatum": "WGS84",
    "georefSources": "GPS",
    "habitat": "Acacia karroo scrubland, pale sandy loam soils",
    "verbatimElevation": "",
    'sitecode': 'ARB12',
    "permitNumber": "",
    "collectingDate": "",
    "startdate": "2015/07/17",
    "enddate": "2015/07/19",
    "collectors": "I. Engelbrecht (UP); D. Kambas",
    "collectMethods": "road cruise",
    "conditions": "",
    "lifeStageSexCounts": "3ad♂",
    "seriesNote": "presumed conspecific with IE15-017",
    "canonicalName": "Harpactirella",
    "taxonRank": "genus",
    "author": "",
    "verbatimIdentification": "",
    "dateIdentified": "2015-07-17",
    "identifiedBy": "I. Engelbrecht (UP)",
    "detMethod": "tacit expertise",
    "identificationQualifier": null,
    "identificationConfidence": 'asd',
    "detReferences": "",
    "detNote": ""
  },
  {
    "catnum": "",
    "collectorNo": "",
    "typestatus": "",
    "country": "South Africa",
    "admin1": "Limpopo",
    "admin1Type": "Prov.",
    "admin2": "Phalaborwa",
    "admin2Type": "Distr.",
    "locality": "Kruger National Park, Shingwedzi Research Camp, Area W of airstrip",
    "verbatimLatitude": "S23°06'59.3\"",
    "verbatimLongitude": "E31°25'38.9\"",
    "uncertainty": null,
    "uncertaintyUnit": "",
    "geodeticDatum": "WGS84",
    "georefSources": "GPS",
    "habitat": "Plain with gentle slope and E aspect; Mopane woodland; dark grey/black clay loam soils",
    "verbatimElevation": "273m",
    'sitecode': '',
    "permitNumber": "RB/06/82",
    "collectingDate": "2007/01/02 08:00–11:30",
    "startdate": "",
    "enddate": "",
    "collectors": "Spider Club members (SCSA)",
    "collectMethods": "opportunistic searching",
    "conditions": "soil wet",
    "lifeStageSexCounts": "",
    "seriesNote": "Many newly dispersed juveniles seen in the field, and one female had babies in the burrow, SCSA07-296 to 336",
    "class": "Arachnida",
    "order": "Araneae",
    "family": "Theraphosidae",
    "genus": "Ceratogyrus",
    "specificEpithet": "bechuanicus",
    "infraspecificEpithet": "",
    "canonicalName": "Ceratogyrus bechuanicus",
    "taxonRank": "species",
    "author": "Purcell, 1902",
    "dateIdentified": "2007-01-02",
    "identifiedBy": "I. Engelbrecht (GDACE)",
    "detMethod": "tacit expertise",
    "identificationQualifier": 'sensu lato',
    "identificationConfidence": '',
    "detReferences": "",
    "detNote": ""
  }
 ]

 export default exampleData