const exampleData = [
  {
    "CATEGORY": "PS",
    "ACCESSION": "",
    "BARCODE": "PRE0857308-0",
    "COLLECTOR": "Masupa, T.T.",
    "PREFIX": "",
    "NUMBER": 8,
    "SUFFIX": "",
    "ADDCOLL": "Kondlo, M.; Magoele, M. & Mogale, M.",
    "DUPS": "PRE",
    "DAY": 5,
    "MONTH": 2,
    "YEAR": 2014,
    "COLLECTED": "05-Feb-14",
    "FAMILY": "Aizoaceae",
    "ALTFAMILY": "",
    "TAXSTAT": "acc",
    "SPECIES": "Mesembryanthemum cordifolium L.f.",
    "FULLNAME": "Mesembryanthemum cordifolium L.f.",
    "ACCEPTED": "Mesembryanthemum cordifolium L.f.",
    "CURATENAME": "Aptenia cordifolia (L.f.) Schwantes",
    "DETSTATUS": "",
    "DETBY": "Phaliso, N",
    "DETDAY": 11,
    "DETMONTH": 3,
    "DETYEAR": 2014,
    "DETDATE": "11-Mar-14",
    "PLANTDESC": "Plant height: 30 cm. Leaves shiny succulent green.",
    "COUNTRY": "South Africa",
    "MAJORAREA": "Gauteng",
    "LOCNOTES": "Melville Koppies Nature Reserve.",
    "HABITATTXT": "Hill slope. Moderate slope.",
    "CULTIVATED": "No",
    "LAT": 26.1607,
    "NS": "S",
    "LONG": 28.0005,
    "EW": "E",
    "LLUNIT": "DMS",
    "LLRES": "1/4dg",
    "LLDATUM": "",
    "QDS": "2628AC",
    "LATDEC": -26.26861111,
    "LONGDEC": 28.00138889,
    "ALT": 1747,
    "ALTUNIT": "",
    "NOTES": "",
    "GENUS": "Mesembryanthemum",
    "SP1": "cordifolium",
    "AUTHOR1": "L.f.",
    "RANK1": "",
    "SP2": "",
    "AUTHOR2": "",
    "RANK2": "",
    "SP3": "",
    "AUTHOR3": "",
    "LABELTOTAL": 0
  },
  {
    "CATEGORY": "PS",
    "ACCESSION": "",
    "BARCODE": "PRE0857598-0",
    "COLLECTOR": "Cheek, M.D.",
    "PREFIX": "",
    "NUMBER": 1978,
    "SUFFIX": "",
    "ADDCOLL": "",
    "DUPS": "NH,PRE",
    "DAY": 18,
    "MONTH": 2,
    "YEAR": 2014,
    "COLLECTED": "18-Feb-14",
    "FAMILY": "Poaceae",
    "ALTFAMILY": "Graminae",
    "TAXSTAT": "acc",
    "SPECIES": "Coix lacryma-jobi L.",
    "FULLNAME": "Coix lacryma-jobi L.",
    "ACCEPTED": "",
    "CURATENAME": "",
    "DETSTATUS": "",
    "DETBY": "Cheek, MD",
    "DETDAY": 0,
    "DETMONTH": 3,
    "DETYEAR": 2014,
    "DETDATE": "Mar-14",
    "PLANTDESC": "2m high. Green round fruit, yellow exerted anthers.",
    "COUNTRY": "South Africa",
    "MAJORAREA": "KwaZulu-Natal",
    "LOCNOTES": "Richmond, Highover Nature Reserve along the Umkomazi River.",
    "HABITATTXT": "River/stream bank. Vegetation type: Eastern Valley Bushveld. Slope: none.",
    "CULTIVATED": "No",
    "LAT": 29.091,
    "NS": "S",
    "LONG": 30.0907,
    "EW": "E",
    "LLUNIT": "DMS",
    "LLRES": "100m",
    "LLDATUM": "",
    "QDS": "2930AA",
    "LATDEC": -29.15277778,
    "LONGDEC": 30.15194444,
    "ALT": 566,
    "ALTUNIT": "",
    "NOTES": "Early Detection and Rapid Response Programme. A  few plants seen; not abundant; no herbivors seen.",
    "GENUS": "Coix",
    "SP1": "lacryma-jobi",
    "AUTHOR1": "L.",
    "RANK1": "",
    "SP2": "",
    "AUTHOR2": "",
    "RANK2": "",
    "SP3": "",
    "AUTHOR3": "",
    "LABELTOTAL": 0
  },
  {
    "CATEGORY": "PS",
    "ACCESSION": "",
    "BARCODE": "PRE0857596-0",
    "COLLECTOR": "Bester, S.P.",
    "PREFIX": "",
    "NUMBER": 12637,
    "SUFFIX": "",
    "ADDCOLL": "Barker, N.P. & Janks, M.R.",
    "DUPS": "PRE",
    "DAY": 14,
    "MONTH": 6,
    "YEAR": 2015,
    "COLLECTED": "14-Jun-15",
    "FAMILY": "Rhamnaceae",
    "ALTFAMILY": "",
    "TAXSTAT": "inc",
    "SPECIES": "Ziziphus mucronata Willd.",
    "FULLNAME": "Ziziphus mucronata Willd.",
    "ACCEPTED": "",
    "CURATENAME": "",
    "DETSTATUS": "",
    "DETBY": "Bester, SP",
    "DETDAY": 10,
    "DETMONTH": 7,
    "DETYEAR": 2015,
    "DETDATE": "10-Jul-15",
    "PLANTDESC": "Tree, to 4 m tall.",
    "COUNTRY": "Botswana",
    "MAJORAREA": "Ngamiland",
    "LOCNOTES": "76 km directly SE of Shakawe on road A35 to Maun.",
    "HABITATTXT": "Plain.",
    "CULTIVATED": "No",
    "LAT": 21.05302,
    "NS": "S",
    "LONG": 24.25437,
    "EW": "E",
    "LLUNIT": "DMS",
    "LLRES": "10m",
    "LLDATUM": "",
    "QDS": "2124AB",
    "LATDEC": -21.09172222,
    "LONGDEC": 24.42880556,
    "ALT": 898,
    "ALTUNIT": "",
    "NOTES": "",
    "GENUS": "Ziziphus",
    "SP1": "mucronata",
    "AUTHOR1": "Willd.",
    "RANK1": "",
    "SP2": "",
    "AUTHOR2": "",
    "RANK2": "",
    "SP3": "",
    "AUTHOR3": "",
    "LABELTOTAL": 2
  },
  {
    "CATEGORY": "PS",
    "ACCESSION": "",
    "BARCODE": "PRE0857597-0",
    "COLLECTOR": "Barker, N.P.",
    "PREFIX": "",
    "NUMBER": 292,
    "SUFFIX": "",
    "ADDCOLL": "Bester, S.P. & Janks, M.R.",
    "DUPS": "PRE",
    "DAY": 11,
    "MONTH": 6,
    "YEAR": 2015,
    "COLLECTED": "11-Jun-15",
    "FAMILY": "Asparagaceae",
    "ALTFAMILY": "",
    "TAXSTAT": "acc",
    "SPECIES": "Asparagus africanus Lam.",
    "FULLNAME": "Asparagus africanus Lam.",
    "ACCEPTED": "",
    "CURATENAME": "",
    "DETSTATUS": "",
    "DETBY": "Burrows, JE",
    "DETDAY": 26,
    "DETMONTH": 8,
    "DETYEAR": 2015,
    "DETDATE": "26-Aug-15",
    "PLANTDESC": "",
    "COUNTRY": "Angola",
    "MAJORAREA": "Cuando Cubango",
    "LOCNOTES": "M'Pupa Airstrip, 1 km SW of Falls.",
    "HABITATTXT": "Plain.",
    "CULTIVATED": "No",
    "LAT": 17.30522,
    "NS": "S",
    "LONG": 20.0333,
    "EW": "E",
    "LLUNIT": "DMS",
    "LLRES": "100m",
    "LLDATUM": "",
    "QDS": "1720CA",
    "LATDEC": -17.5145,
    "LONGDEC": 20.05916667,
    "ALT": 1072,
    "ALTUNIT": "",
    "NOTES": "",
    "GENUS": "Asparagus",
    "SP1": "africanus",
    "AUTHOR1": "Lam.",
    "RANK1": "",
    "SP2": "",
    "AUTHOR2": "",
    "RANK2": "",
    "SP3": "",
    "AUTHOR3": "",
    "LABELTOTAL": 2
  },
  {
    "CATEGORY": "PS",
    "ACCESSION": "",
    "BARCODE": "PRE0857592-0",
    "COLLECTOR": "Zietsman, P.C.",
    "PREFIX": "",
    "NUMBER": 5705,
    "SUFFIX": "",
    "ADDCOLL": "Zietsman, L.",
    "DUPS": "PRE",
    "DAY": 16,
    "MONTH": 4,
    "YEAR": 2014,
    "COLLECTED": "16-Apr-14",
    "FAMILY": "Acanthaceae",
    "ALTFAMILY": "",
    "TAXSTAT": "acc",
    "SPECIES": "Crabbea angustifolia Nees",
    "FULLNAME": "Crabbea angustifolia Nees",
    "ACCEPTED": "",
    "CURATENAME": "",
    "DETSTATUS": "",
    "DETBY": "Steyn, H",
    "DETDAY": 0,
    "DETMONTH": 7,
    "DETYEAR": 2014,
    "DETDATE": "Jul-14",
    "PLANTDESC": "Herb. Plant height: 2 cm. Prostrate. Flowers light yellow.",
    "COUNTRY": "South Africa",
    "MAJORAREA": "Limpopo",
    "LOCNOTES": "Thabazimbi District. Farm Maritikloof 380, about 25 km SE from Thabazimbi.",
    "HABITATTXT": "Plain. Scattered.",
    "CULTIVATED": "No",
    "LAT": 24.4224,
    "NS": "S",
    "LONG": 27.2912,
    "EW": "E",
    "LLUNIT": "DMS",
    "LLRES": "100m",
    "LLDATUM": "",
    "QDS": "2427CB",
    "LATDEC": -24.70666667,
    "LONGDEC": 27.48666667,
    "ALT": 964,
    "ALTUNIT": "",
    "NOTES": "",
    "GENUS": "Crabbea",
    "SP1": "angustifolia",
    "AUTHOR1": "Nees",
    "RANK1": "",
    "SP2": "",
    "AUTHOR2": "",
    "RANK2": "",
    "SP3": "",
    "AUTHOR3": "",
    "LABELTOTAL": 0
  },
  {
    "CATEGORY": "PS",
    "ACCESSION": "",
    "BARCODE": "PRE0857594-0",
    "COLLECTOR": "Zietsman, P.C.",
    "PREFIX": "",
    "NUMBER": 5669,
    "SUFFIX": "",
    "ADDCOLL": "Zietsman, L. & Nel, E.",
    "DUPS": "PRE",
    "DAY": 6,
    "MONTH": 4,
    "YEAR": 2014,
    "COLLECTED": "06-Apr-14",
    "FAMILY": "Asteraceae",
    "ALTFAMILY": "Compositae",
    "TAXSTAT": "acc",
    "SPECIES": "Felicia muricata (Thunb.) Nees subsp. muricata",
    "FULLNAME": "Felicia muricata (Thunb.) Nees subsp. muricata",
    "ACCEPTED": "",
    "CURATENAME": "",
    "DETSTATUS": "",
    "DETBY": "Herman, PPJ",
    "DETDAY": 0,
    "DETMONTH": 7,
    "DETYEAR": 2014,
    "DETDATE": "Jul-14",
    "PLANTDESC": "Herb. Plant height: 40 cm.",
    "COUNTRY": "South Africa",
    "MAJORAREA": "Northern Cape",
    "LOCNOTES": "Herbert District. Mokala National Park : near Lilydale Gate.",
    "HABITATTXT": "Plain. Few.",
    "CULTIVATED": "No",
    "LAT": 29.0423,
    "NS": "S",
    "LONG": 24.28,
    "EW": "E",
    "LLUNIT": "DMS",
    "LLRES": "100m",
    "LLDATUM": "",
    "QDS": "2924AB",
    "LATDEC": -29.07305556,
    "LONGDEC": 24.46666667,
    "ALT": 1148,
    "ALTUNIT": "",
    "NOTES": "",
    "GENUS": "Felicia",
    "SP1": "muricata",
    "AUTHOR1": "(Thunb.) Nees",
    "RANK1": "subsp.",
    "SP2": "muricata",
    "AUTHOR2": "",
    "RANK2": "",
    "SP3": "",
    "AUTHOR3": "",
    "LABELTOTAL": 0
  },
  {
    "CATEGORY": "PS",
    "ACCESSION": "",
    "BARCODE": "PRE0857599-0",
    "COLLECTOR": "Jaca, T.",
    "PREFIX": "",
    "NUMBER": 649,
    "SUFFIX": "",
    "ADDCOLL": "Miza, S.",
    "DUPS": "PRE",
    "DAY": 4,
    "MONTH": 3,
    "YEAR": 2014,
    "COLLECTED": "04-Mar-14",
    "FAMILY": "Poaceae",
    "ALTFAMILY": "Graminae",
    "TAXSTAT": "acc",
    "SPECIES": "Cortaderia selloana (Schult.) Asch. & Graebn.",
    "FULLNAME": "Cortaderia selloana (Schult.) Asch. & Graebn.",
    "ACCEPTED": "",
    "CURATENAME": "",
    "DETSTATUS": "",
    "DETBY": "Mashau, AC",
    "DETDAY": 0,
    "DETMONTH": 9,
    "DETYEAR": 2014,
    "DETDATE": "Sep-14",
    "PLANTDESC": "Graminoid. Plant height: 2.2 m. Leaves sticky.",
    "COUNTRY": "South Africa",
    "MAJORAREA": "Mpumalanga",
    "LOCNOTES": "R537; about 12 km to Sabie.",
    "HABITATTXT": "Hillslope. Slope: moderate.",
    "CULTIVATED": "No",
    "LAT": 25.104,
    "NS": "S",
    "LONG": 30.5124,
    "EW": "E",
    "LLUNIT": "DMS",
    "LLRES": "50m",
    "LLDATUM": "",
    "QDS": "2530BB",
    "LATDEC": -25.17777778,
    "LONGDEC": 30.85666667,
    "ALT": 0,
    "ALTUNIT": "",
    "NOTES": "",
    "GENUS": "Cortaderia",
    "SP1": "selloana",
    "AUTHOR1": "(Schult.) Asch. & Graebn.",
    "RANK1": "",
    "SP2": "",
    "AUTHOR2": "",
    "RANK2": "",
    "SP3": "",
    "AUTHOR3": "",
    "LABELTOTAL": 0
  }
 ]
export default exampleData